### PR TITLE
Add preshared key for client 

### PR DESCRIPTION
**Pull request by flier**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

------------------------------

 - [x] I have read the [contributing](https://github.com/linuxserver/docker-wireguard/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description:

Add a preshared key when automatically generating client configurations.
> If an additional layer of symmetric-key crypto is required (for, say, post-quantum resistance), WireGuard also supports an optional pre-shared key that is mixed into the public key cryptography. When pre-shared key mode is not in use, the pre-shared key value used below is assumed to be an all-zero string of 32 bytes.

## Benefits of this PR and context:

Provides an additional layer of symmetric-key crypto.

## Source / References:

* [Protocol & Cryptography / Key Exchange and Data Packets](https://www.wireguard.com/protocol/#key-exchange-and-data-packets)
* [WireGuard / Key generation](https://wiki.archlinux.org/index.php/WireGuard#Key_generation)

### CODE REVIEW

**Comment by ksurl** [comment]
Should it be created by default? Or enabled via environment variable

**Comment by flier** [comment]
> Should it be created by default? Or enabled via environment variable

For me, the default enable is the most appropriate, more secure and with controlled performance loss.

**Comment by anoma** [comment]
What are the potential downsides of this. There have to be some as otherwise it would be a more universally accepted default.

**Comment by aptalca** [comment]
Aside from any potential downsides of the preshared key, this PR would break all existing installs because 1. peer template won't get auto updated for users (we don't touch user customizable files) so peer confs won't get it
And 2. Preshared key will be added for all peers in wg0.conf and it will require all existing confs to be updated on all client machines

**Comment by flier** [comment]
hi @anoma 

Compatibility will indeed be an issue, but at least the new server will have an additional, more secure option.


Hi @aptalca 

I think we could use a `PRESHARED_KEY=on` parameter to enable it.

**Comment by walle89** [comment]
I think adding PRESHARED_KEY as environment setting seems like a good solution. It would be really nice to have support for preshared key.

**Comment by michaelkrieger** [comment]
The PSK is now per-peer (versus per server), so it could easily be generated only on the addition of new configurations.  The PSK is a 256-bit key (such as that generated with wg genpsk).  Wireguard ALWAYS computes with a PSK (of all zeros), so there is no performance impact of including one versus not including one, but unfortunately a 000...000= PSK doesn't match with a client that isn't using PSKs at all.

Simply generating this in `root/app/add-peer` only when generating new client certificates and a new configuration will accomplish the goal of phasing this in for new installations as well as new peers, without breaking any old peers.  Consider this (instead of generating the PSK separately from the main key).
```
if [ ! -f "/config/${PEER_ID}/privatekey-${PEER_ID}" ]; then
  umask 077
  wg genkey | tee /config/${PEER_ID}/privatekey-${PEER_ID} | wg pubkey > /config/${PEER_ID}/publickey-${PEER_ID}
  if [ "$PRESHARED_KEY" == "on" ]; then
    if [ ! -f "/config/${PEER_ID}/presharedkey-${PEER_ID}" ]; then
      umask 077
      wg genpsk | tee /config/${PEER_ID}/presharedkey-${PEER_ID}
    fi
  fi
fi
```

In the generating of the config files (in `root/app/add-peer`), you can simply test if the PSK exists and add it to the config if it does, without any attempt to generate it.
```
if [ "$PRESHARED_KEY" == "on" ]; then
  if [ -f /config/peer${i}/presharedkey-peer${i} ]; then
    cat <<DUDE >> /config/wg0.conf
PresharedKey = $(cat /config/peer${i}/presharedkey-peer${i})
DUDE
    cat <<DUDE >> /config/peer${i}/peer${i}.conf
PresharedKey = $(cat /config/peer${i}/presharedkey-peer${i})
DUDE
  fi
fi
```

And the same deal in `root/etc/cont-init.d/30-config`

Happy to do this as a new PR if it's helpful.

**Comment by walle89** [comment]
@michaelkrieger Sounds good to me. But that's just my opinion. Any action to move on with this PR is a step in the right direction.

**Comment by michaelkrieger** [comment]
Bumpity. Still valid

**Comment by shawly** [comment]
Will this be merged any time soon?

**Comment by michaelkrieger** [comment]
Still valid

**Comment by egooner** [comment]
Just come across this one ... I was wanting the same thing ... but looking at the existing code I realised that we could do it ourselves!!!
I made the following changes all in the config folder which is mounted to docker - I think it will therefore survive updates!?
Perhaps someone else will find this useful!!

**templates/peer.conf**

Add this line to the [Peer] section, it will check for existence of a file called psk-*PEER_ID* and if found use it otherwise generate and save to psk-*PEER_ID* in the config Peer sub folder
```
PresharedKey = $(if [[ -e "/config/${PEER_ID}/psk-${PEER_ID}" ]]; then cat "/config/${PEER_ID}/psk-${PEER_ID}"; else wg genpsk | tee "/config/${PEER_ID}/psk-${PEER_ID}"; fi)
```

Then create a script in the custom init directory, this will run after the files have been generated but critically will update the wg0.conf file which is used by the server. Once you have done this shutdown Wireguard container and delete wg0.conf in the mount area. 

**custom-cont-init.d/10-add-psk**

```
#!/usr/bin/with-contenv bash

# Run this to add Pre Shared Keys
CONFPATH=${1:-/config}
#
# Find all files with Pre Shared Keys
scan_peer() {
  local psk peer=$1
  echo "Processing Peer Configuration for Peer : $peer"
  if [[ -e ${CONFPATH}/${peer}/${peer}.conf && -f ${CONFPATH}/${peer}/${peer}.conf ]]; then
    echo "... Checking Peer Configuration File"
    psk=$(grep -i "presharedkey" ${CONFPATH}/${peer}/${peer}.conf)
    if [[ "${psk}" == "" ]]; then
      echo "... Configuration skipped as no Pre Shared Key Found"
    else
      echo "... PresharedKey Found adding to Hash"
      PSKLIST[$peer]=$psk
    fi
  else
    echo "... Error : Peer Configuration File Not Found"
  fi
}

find_peers() {
  local peers filename
  peers=$(find ${CONFPATH}/peer_* -maxdepth 1 -type d -exec basename {} \;)
  while read -r filename; 
  do
    scan_peer "$filename"
  done <<< ${peers}
}

update_wg_file() {
  local line inpeer=0 peername="" haspsk=0
  if [[ -e "${CONFPATH}/wg0.conf.backup" ]]; then
    rm "${CONFPATH}/wg0.conf.backup"
  fi
  cp ${CONFPATH}/wg0.conf ${CONFPATH}/wg0.conf.backup
  if [[ -e "${CONFPATH}/wg0.conf.backup" ]]; then
    cp /dev/null ${CONFPATH}/wg0.conf
    while read -r line;
    do
      if [[ $line =~ "# peer_" ]]; then
        inpeer=1
        peername=${line:2}
        echo "Processing WG0 Peer : ${peername}"
      fi
      if [[ $inpeer -eq 1 ]]; then
        if [[ $line =~ "PresharedKey" ]]; then
          haspsk=1
          echo "... already has a presharedkey"
        elif [[ "$line" == "" ]]; then
          if [[ $haspsk -eq 0 ]]; then
            echo "... adding presharedkey"
            echo "${PSKLIST[${peername}]}" >> ${CONFPATH}/wg0.conf
          fi
          inpeer=0
          haspsk=0
        fi
      fi
      echo "$line" >> ${CONFPATH}/wg0.conf
    done < "${CONFPATH}/wg0.conf.backup"
  else
    echo "ERROR : Failed to make backup of wg0.conf, processing aborted"
  fi
}

run() {
  declare -A -g PSKLIST
  if [[ -e "${CONFPATH}/wg0.conf" ]]; then
    find_peers 
    update_wg_file
  else
    echo "ERROR : Missing wg0.conf file, processing halted"
  fi
}

echo "Finding Peer Configurations with Pre Shared Keys"
run
```

**Comment by walle89** [comment]
Still valid, what needs to be done to move this pull request forward?

**Comment by aptalca** [comment]
Needs to be backwards compatible without a new var (always on for new peers, but off for existing peers)

**Comment by walle89** [comment]
> Needs to be backwards compatible without a new var (always on for new peers, but off for existing peers)

I think https://github.com/walle89/docker-wireguard/commit/68cc847084ff023d9527e0916e416ed6d27fce11 should do the trick, I haven't done a more extensive testing yet. Soon as I have done that I can either create a new pull request or post a comment with suggested changes.

**Comment by aptalca** [comment]
That wouldn't work, but I had some time to put in a PR: https://github.com/linuxserver/docker-wireguard/pull/165

Please test this image and let me know: `lspipepr/wireguard:v1.0.20210914-pkg-6544b33e-pr-165`

**Comment by walle89** [comment]
> That wouldn't work, but I had some time to put in a PR: #165
> 
> Please test this image and let me know: `lspipepr/wireguard:v1.0.20210914-pkg-6544b33e-pr-165`
Yep, found out it was a bit buggy so I did a fix for it: https://github.com/walle89/docker-wireguard/compare/master...preshared-key

But I see that you solved it with a different approach, and I think I like it a bit more than what I came up with. I will test it out.

**Pull request closed without merging**
