### PR TITLE
Run on amazon linux host

### PR DESCRIPTION
**Pull request by zhuker**
This modifies the init script to download amazon linux kernel headers if host machine is amazon linux 2.

[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

------------------------------

 - [x] I have read the [contributing](https://github.com/linuxserver/docker-wireguard/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description:

Add amazon linux 2 rpm repositories
Check for `amzn2` in `uname -r`
Download and install appropriate headers
Keep the compile script the same

## Benefits of this PR and context:

Now you can run this docker image on AWS

## How Has This Been Tested?

By running on k8s deployed in aws

## Source / References:

This PR may be relevant to https://github.com/linuxserver/docker-wireguard/issues/84

### CODE REVIEW

**Comment by zhuker** [comment]
@aptalca any comments?

**Comment by erbesharat** [comment]
Any updates from the maintainers? We really would appreciate having this feature merged.

**Comment by drizuid** [comment]
I think this is better created as a mod. We have no intention of offering support for non ubuntu or alpine systems for our containers, adding this in implicitly adds an additional support requirement.  I suggest you look below and create a mod to accomplish this goal. 
https://www.linuxserver.io/blog/2019-09-14-customizing-our-containers

**Comment by jodevsa** [comment]
@drizuid  can you elaborate more on the reason?  can't the community support it :) ?

**Pull request closed without merging**
